"""
Django settings for hotel_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEFAULT_INSECURE_SECRET = 'django-insecure-CHANGE-THIS-IN-PRODUCTION'
SECRET_KEY = config('SECRET_KEY', default=DEFAULT_INSECURE_SECRET)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

if not DEBUG and (
    not SECRET_KEY
    or SECRET_KEY == DEFAULT_INSECURE_SECRET
    or SECRET_KEY.startswith('django-insecure-')
):
    raise ImproperlyConfigured(
        'SECRET_KEY insegura para producción. Define una clave robusta en .env.'
    )

ALLOWED_HOSTS = [
    host for host in config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv()) if host
]
CSRF_TRUSTED_ORIGINS = [
    origin for origin in config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv()) if origin
]

if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        'ALLOWED_HOSTS vacío en producción. Define hosts válidos en .env.'
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Nuestras apps
    'reservas',  # 👈 Añadimos nuestra app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # 🌍 i18n - Debe estar después de SessionMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'reservas.middleware.RatelimitMiddleware',  # 🔒 Rate limiting middleware
]

ROOT_URLCONF = 'hotel_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hotel_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database - Configuración flexible para desarrollo y producción
DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.sqlite3'),
        'NAME': config('DB_NAME', default=str(BASE_DIR / 'db.sqlite3')),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default=''),
        'PORT': config('DB_PORT', default=''),
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=60, cast=int),
        'CONN_HEALTH_CHECKS': config('DB_CONN_HEALTH_CHECKS', default=True, cast=bool),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 🌍 Internationalization (i18n)
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'  # Idioma por defecto
LANGUAGES = [
    ('es', 'Español'),
    ('gl', 'Galego'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',  # � Carpeta donde guardar traducciones
]

TIME_ZONE = 'Europe/Madrid'  # Zona horaria de España

USE_I18N = True  # ✅ Habilitar i18n
USE_L10N = True  # Localización

USE_TZ = True

# Use BigAutoField for implicit primary keys in new models/apps.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# 📂 Carpeta con archivos estáticos del proyecto (CSS, imágenes, JS propios)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Para producción - Carpeta donde collectstatic recopila todos los archivos estáticos
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 📂 Media files (archivos subidos por usuarios)
# 🎓 CONCEPTO: MEDIA = fotos, PDFs, etc. subidos por usuarios
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # 🐍 Carpeta donde se guardan

# 🔒 Autenticación
LOGIN_URL = 'login'  # 👈 Redirigir al login si no está autenticado
LOGIN_REDIRECT_URL = 'home'  # 👈 Redirigir al home después de login
LOGOUT_REDIRECT_URL = 'home'  # 👈 Redirigir al home después de logout

# 🔒 Configuración de seguridad para producción
# Estas configuraciones se activan automáticamente cuando DEBUG=False
if not DEBUG:
    # Si hay reverse proxy (Nginx/Traefik), habilitar esta opción en .env
    if config('BEHIND_PROXY', default=False, cast=bool):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # HTTPS/SSL
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)
    SESSION_COOKIE_HTTPONLY = config('SESSION_COOKIE_HTTPONLY', default=True, cast=bool)
    CSRF_COOKIE_HTTPONLY = config('CSRF_COOKIE_HTTPONLY', default=True, cast=bool)

    SESSION_COOKIE_SAMESITE = config('SESSION_COOKIE_SAMESITE', default='Lax')
    CSRF_COOKIE_SAMESITE = config('CSRF_COOKIE_SAMESITE', default='Lax')

    valid_samesite = {'Lax', 'Strict', 'None'}
    if SESSION_COOKIE_SAMESITE not in valid_samesite:
        raise ImproperlyConfigured(
            'SESSION_COOKIE_SAMESITE inválido. Usa Lax, Strict o None.'
        )
    if CSRF_COOKIE_SAMESITE not in valid_samesite:
        raise ImproperlyConfigured(
            'CSRF_COOKIE_SAMESITE inválido. Usa Lax, Strict o None.'
        )
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True, cast=bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=True, cast=bool)
    
    # Otras configuraciones de seguridad
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'same-origin'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
