# Generated by Django 6.0.2 on 2026-02-19 22:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número de habitación (ej: 101, 205)', max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('doble', 'Doble'), ('suite', 'Suite'), ('familiar', 'Familiar')], default='doble', max_length=20)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio por noche en euros', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('capacidad', models.IntegerField(default=2, help_text='Número máximo de personas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('tiene_vista_mar', models.BooleanField(default=False, verbose_name='Vista al mar')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la habitación', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['numero'],
                'indexes': [models.Index(fields=['tipo'], name='reservas_ha_tipo_e7b984_idx'), models.Index(fields=['precio_base'], name='reservas_ha_precio__10e628_idx')],
            },
        ),
    ]
