# Generated by Django 6.0.2 on 2026-02-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto principal de la habitación', null=True, upload_to='habitaciones/'),
        ),
    ]
