# Generated by Django 6.0.2 on 2026-02-19 22:29

import django.core.validators
import django.db.models.deletion
import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_habitacion_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('dni_nie', models.CharField(help_text='DNI o NIE español (ej: 12345678Z o X1234567L)', max_length=9, unique=True, validators=[reservas.models.validar_dni_nie])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('pais', models.CharField(default='España', max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Formato: YYYY-MM-DD', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, help_text='Preferencias, alergias, etc.')),
                ('es_vip', models.BooleanField(default=False, verbose_name='Cliente VIP')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField(verbose_name='Fecha de entrada (Check-in)')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida (Check-out)')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación de la reserva')),
                ('numero_adultos', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('numero_ninos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_por_noche', models.DecimalField(decimal_places=2, help_text='Precio por noche al momento de la reserva', max_digits=8)),
                ('precio_total', models.DecimalField(decimal_places=2, editable=False, help_text='Precio total de la estancia', max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('confirmada', 'Confirmada'), ('en_curso', 'En curso (Check-in realizado)'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Peticiones especiales, hora estimada de llegada, etc.')),
                ('pagado', models.BooleanField(default=False, verbose_name='¿Pagado?')),
                ('cliente', models.ForeignKey(help_text='Cliente que realiza la reserva', on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.cliente')),
                ('habitacion', models.ForeignKey(help_text='Habitación reservada', on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.habitacion')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_reserva'],
            },
        ),
    ]
