# Generated by Django 5.0.2 on 2026-03-15 17:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_cliente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDelDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, help_text='Fecha del menú', unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Si hay varios menús activos, se muestra el más reciente')),
                ('consumicion_incluida', models.CharField(default='Incluye una consumición: vino, cerveza, refresco o agua', max_length=120)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Menú del día',
                'verbose_name_plural': 'Menús del día',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterField(
            model_name='reserva',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Peticiones especiales, hora estimada de llegada, etc.', max_length=500),
        ),
        migrations.CreateModel(
            name='PlatoMenuDelDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('primero', 'Primer plato'), ('segundo', 'Segundo plato'), ('postre', 'Postre')], max_length=10)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('disponible', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='reservas.menudeldia')),
            ],
            options={
                'verbose_name': 'Plato del menú del día',
                'verbose_name_plural': 'Platos del menú del día',
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
    ]
