# Generated by Django 5.0.2 on 2026-03-15 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_menudeldia_alter_reserva_observaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Menú de Semana Santa, Menú Degustación Gallego…', max_length=120)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve del menú especial')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Precio por persona (dejar vacío si no aplica)', max_digits=6, null=True)),
                ('fecha_inicio', models.DateField(help_text='Primer día en que se ofrece el menú especial')),
                ('fecha_fin', models.DateField(help_text='Último día en que se ofrece el menú especial')),
                ('activo', models.BooleanField(default=True)),
                ('consumicion_incluida', models.CharField(blank=True, help_text='Ej: Vino de la casa incluido', max_length=120)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Menú especial',
                'verbose_name_plural': 'Menús especiales',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlatoMenuEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('primero', 'Primer plato'), ('segundo', 'Segundo plato'), ('postre', 'Postre'), ('extra', 'Extra / Maridaje')], max_length=10)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('disponible', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='reservas.menuespecial')),
            ],
            options={
                'verbose_name': 'Plato del menú especial',
                'verbose_name_plural': 'Platos del menú especial',
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
    ]
