# Generated by Django 5.0.2 on 2026-03-15 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_menuespecial_platomenuespecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='checkin_online_completado',
            field=models.BooleanField(default=False, help_text='Indica si se completó el check-in online legal.'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='contrato_aceptado',
            field=models.BooleanField(default=False, help_text='Consentimiento del contrato de hospedaje.'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='iban',
            field=models.CharField(blank=True, help_text='IBAN asociado a la transacción (si aplica).', max_length=34),
        ),
        migrations.AddField(
            model_name='reserva',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia bancaria'), ('efectivo', 'Efectivo'), ('bizum', 'Bizum'), ('otro', 'Otro')], help_text='Medio de pago informado por el viajero principal.', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='relaciones_parentesco_adultos',
            field=models.TextField(blank=True, help_text='Relación de parentesco entre viajeros mayores de edad.'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='ses_hospedajes_enviado',
            field=models.BooleanField(default=False, help_text='Indica si el parte fue enviado al servicio web SES Hospedajes.'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='ses_hospedajes_referencia',
            field=models.CharField(blank=True, help_text='Referencia o identificador devuelto por SES Hospedajes.', max_length=120),
        ),
        migrations.CreateModel(
            name='ViajeroCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No especificado')], max_length=1)),
                ('tipo_documento', models.CharField(choices=[('dni', 'DNI'), ('nie', 'NIE/TIE'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro documento')], max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=30)),
                ('numero_soporte', models.CharField(blank=True, max_length=30)),
                ('nacionalidad', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion_residencia', models.CharField(max_length=200)),
                ('ciudad_residencia', models.CharField(max_length=100)),
                ('codigo_postal_residencia', models.CharField(max_length=12)),
                ('pais_residencia', models.CharField(default='España', max_length=80)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('relacion_con_titular', models.CharField(choices=[('titular', 'Titular de la reserva'), ('conyuge', 'Cónyuge/pareja'), ('hijo', 'Hijo/a'), ('padre_madre', 'Padre/Madre'), ('familiar', 'Familiar'), ('amigo', 'Amigo/a'), ('otro', 'Otro')], default='titular', max_length=20)),
                ('es_menor_sin_documento', models.BooleanField(default=False)),
                ('parentesco_menor_con_adulto', models.CharField(blank=True, max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajeros_checkin', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Viajero de check-in',
                'verbose_name_plural': 'Viajeros de check-in',
                'ordering': ['orden', 'id'],
                'unique_together': {('reserva', 'orden')},
            },
        ),
    ]
