# Generated by Django 5.0.2 on 2026-07-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_reserva_checkin_online_completado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudeldia',
            name='activo',
            field=models.BooleanField(default=True, help_text='Publicar u ocultar el menú del día'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['habitacion', 'fecha_salida', 'fecha_entrada'], name='reservas_re_habitac_56eabc_idx'),
        ),
    ]
