# Generated by Django 5.0.2 on 2026-08-17 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_menudeldia_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='checkin_online_omitido',
            field=models.BooleanField(default=False, help_text='Indica si el huésped omitió el check-in online.'),
        ),
        migrations.CreateModel(
            name='ConsentimientoRGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consentimiento', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del consentimiento')),
                ('texto_consentimiento', models.TextField(help_text='Texto exacto aceptado por el cliente')),
                ('version_politica', models.CharField(help_text='Versión de la política de privacidad aceptada', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde la que se dio el consentimiento', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User-Agent del navegador', max_length=500)),
                ('revocado', models.BooleanField(default=False, help_text='Indica si el consentimiento fue revocado')),
                ('fecha_revocacion', models.DateTimeField(blank=True, help_text='Fecha de revocación del consentimiento', null=True)),
                ('motivo_revocacion', models.TextField(blank=True, help_text='Motivo de la revocación (opcional)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente que da el consentimiento', on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos_rgpd', to='reservas.cliente')),
                ('reserva', models.ForeignKey(help_text='Reserva asociada al consentimiento', on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos_rgpd', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Consentimiento RGPD',
                'verbose_name_plural': 'Consentimientos RGPD',
                'ordering': ['-fecha_consentimiento'],
                'unique_together': {('reserva', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la acción')),
                ('tipo_accion', models.CharField(choices=[('creacion', 'Creación de registro'), ('modificacion', 'Modificación de datos'), ('eliminacion', 'Eliminación/anonimización'), ('acceso', 'Acceso a datos'), ('envio_ses', 'Envío a SES Hospedajes'), ('ejercicio_derechos', 'Ejercicio de derechos RGPD'), ('consentimiento', 'Consentimiento dado'), ('revocacion', 'Consentimiento revocado')], help_text='Tipo de acción realizada', max_length=30)),
                ('entidad_tipo', models.CharField(choices=[('reserva', 'Reserva'), ('viajero_checkin', 'Viajero Check-in'), ('consentimiento_rgpd', 'Consentimiento RGPD'), ('cliente', 'Cliente')], help_text='Tipo de entidad afectada', max_length=50)),
                ('entidad_id', models.PositiveIntegerField(help_text='ID de la entidad afectada')),
                ('descripcion', models.TextField(help_text='Descripción de la acción realizada')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Snapshot de datos antes de la modificación', null=True)),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Snapshot de datos después de la modificación', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde la que se realizó la acción', null=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción (null si sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-fecha_accion'],
                'indexes': [models.Index(fields=['fecha_accion'], name='reservas_re_fecha_a_bf4d42_idx'), models.Index(fields=['entidad_tipo', 'entidad_id'], name='reservas_re_entidad_b3ee8c_idx'), models.Index(fields=['usuario'], name='reservas_re_usuario_cef743_idx')],
            },
        ),
    ]
